eureka:
  client:
    # 是否向 Eureka 获取其它服务的信息
    fetch-registry: false
    # 是否向 Eureka 注册自身
    register-with-eureka: false
spring:
  datasource:
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql