-- 用户表，测试基础查询功能
DROP TABLE IF EXISTS person;
CREATE TABLE person
(
	id BIGINT(16) NOT NULL COMMENT '主键ID',
	username VARCHAR(32) NULL DEFAULT NULL COMMENT '姓名',
	firstName VARCHAR(32) NULL DEFAULT NULL COMMENT '姓名',
	lastName VARCHAR(32) NULL DEFAULT NULL COMMENT '姓名',
	birthDate DATE NULL DEFAULT NULL COMMENT '年龄',
);