server:
  port: 8766

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka/
      # 程序员DD的Eureka
      defaultZone: http://eureka.didispace.com/eureka/

spring:
  application:
    name: gateway