DROP TABLE IF EXISTS wt_user;
DROP TABLE IF EXISTS wt_order;

CREATE TABLE wt_user
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT(11) NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	PRIMARY KEY (id)
);

CREATE TABLE wt_order
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	user_id BIGINT(20) NOT NULL COMMENT '用户ID',
	PRIMARY KEY (id)
);