server:
  port: 8772

eureka:
  instance:
    # Use its IP Address rather than its hostname to registers with eureka.
    preferIpAddress: true
  client:
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka.didispace.com/eureka/

spring:
  application:
    name: trade
feign:
  client:
    config:
      default:
        loggerLevel: full